name: Flutter Pages Deployer

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/pages.yml
      - json_theme/pubspec.yaml

jobs:
  build_number:
    runs-on: ubuntu-latest
    outputs:
      buildnumber: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Generate Build Number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Build Number
        run: echo "Build Number - $BUILD_NUMBER"

  publish:
    needs: build_number
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run Codegen
        run: |
          flutter packages get
          dart run build_runner build --delete-conflicting-outputs -v
        working-directory: packages/json_theme

      - name: Validate
        uses: ./.github/actions/flutter-validate
        with:
          path: packages/json_theme

      - name: Build Web
        run: flutter build web --release --no-tree-shake-icons --base-href /flutter_json_schemas/
        working-directory: packages/json_theme/example

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.REPO_TOKEN }}
          external_repository: Ciudad-Valles-Open-Source/flutter_json_schemas
          publish_branch: gh-pages
          publish_dir: packages/json_theme/example/build/web
          keep_files: true
