name: Codegen Publisher

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - packages/codegen/pubspec.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate
        uses: ./.github/actions/flutter-validate
        with:
          path: packages/codegen

      - name: Publish
        uses: ./.github/actions/pub-publish
        with:
          credentials: ${{ secrets.CREDENTIAL_JSON }}
          path: packages/codegen
