name: Flutter Publisher

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/publisher.yml
      - json_theme/pubspec.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run Codegen
        run: |
          flutter packages get
          dart run build_runner build --delete-conflicting-outputs -v
        working-directory: packages/json_theme

      - name: Validate
        uses: ./.github/actions/flutter-validate
        with:
          generate_code: true
          path: packages/json_theme

      - name: Checkout Schemas
        uses: actions/checkout@v4
        with:
          repository: Ciudad-Valles-Open-Source/flutter_json_schemas
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
          ref: gh-pages
          path: schemas

      - name: Update Schemas
        run: |
          git config --global user.email "noop@peifferinnovations.com"
          git config --global user.name "action"
          git config --global url."https://action:${{secrets.REPO_TOKEN}}@github.com/".insteadOf https://github.com/

          rm -rf ../../schemas/schemas/json_theme
          mkdir ../../schemas/schemas/json_theme
          cp output/* ../../schemas/schemas/json_theme
          cd ../../schemas
          git add .
          git commit --allow-empty -m "json_theme: schema update"
          git push origin HEAD:gh-pages
        working-directory: packages/json_theme

      - name: Publish
        uses: ./.github/actions/pub-publish
        with:
          credentials: ${{ secrets.CREDENTIAL_JSON }}
          path: packages/json_theme

      - name: Auto Tag Version
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '"\'')
          TAG="v$VERSION"
          if ! git ls-remote --tags origin | grep -q "refs/tags/$TAG"; then
            git config --global user.email "noop@ciudad-valles-open-source.com"
            git config --global user.name "action"
            git tag -a "$TAG" -m "Release $TAG"
            git push origin "$TAG"
          else
            echo "Tag $TAG already exists."
          fi
        working-directory: packages/json_theme
