name: Dependencies Updater

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 2"

jobs:
  update_dependencies_annotation:
    runs-on: ubuntu-latest

    steps:
      - name: Update Dependencies (packages/annotation)
        run: |
          dart pub global activate dart_dependency_updater
          dart pub global run dart_dependency_updater:update --token ${{ secrets.REPO_TOKEN }} --message "actions-dart-dependency-updater: updating dependencies" --pull-request true --merge true --paths packages/annotation --repository ${{ github.repository }}

  update_dependencies_codegen:
    needs:
      - update_dependencies_annotation
    runs-on: ubuntu-latest

    steps:
      - name: Update Dependencies (packages/codegen)
        run: |
          dart pub global activate dart_dependency_updater
          dart pub global run dart_dependency_updater:update --token ${{ secrets.REPO_TOKEN }} --message "actions-dart-dependency-updater: updating dependencies" --pull-request true --merge true --paths packages/codegen --repository ${{ github.repository }}

  update_dependencies:
    needs:
      - update_dependencies_codegen
    runs-on: ubuntu-latest

    steps:
      - name: Update Dependencies (packages/json_theme,json_theme/example)
        run: |
          dart pub global activate dart_dependency_updater
          dart pub global run dart_dependency_updater:update --token ${{ secrets.REPO_TOKEN }} --message "actions-dart-dependency-updater: updating dependencies" --pull-request true --merge true --paths packages/json_theme,packages/json_theme/example --repository ${{ github.repository }}
